spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://jack:12345@localhost:27017/product-service?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

cors:
  allow:
    origin: http://localhost:8222

server:
  port: 8050

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: product-service
  tracing:
    sampling:
      probability: 1.0
# Loki URL
loki:
  url: http://localhost:3100/loki/api/v1/push

