spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  # Kafka properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-placed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderCreatedEvent:com.dev.order_service.kafka.OrderCreatedEvent,inventoryKafka:com.dev.order_service.kafka.InventoryKafka
        schema:
          registry:
            url: http://127.0.0.1:8085

application:
  config:
    inventory-url: http://localhost:8070

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

cors:
  allow:
    origin: http://localhost:8222


server:
  port: 8060

# Circuit breaker personalizado para esta instancia (Para el RestClient inventory)
# Resilience4j properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  # Resilience4j timeout properties
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
  # Resilience4j retry properties
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: order-service
  tracing:
    sampling:
      probability: 1.0
# Loki URL
loki:
  url: http://localhost:3100/loki/api/v1/push