spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/micro-services

server:
  port: 8222

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      name: Product Service
      url: /aggregate/product-service/v3/api-docs
    urls[1]:
      name: Order Service
      url: /aggregate/order-service/v3/api-docs
    urls[2]:
      name: Inventory Service
      url: /aggregate/inventory-service/v3/api-docs
  api-docs:
    path: /api-docs

product:
  service:
    url: http://localhost:8050
order:
  service:
    url: http://localhost:8060
inventory:
  service:
    url: http://localhost:8070


# Actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: api-gateway
  tracing:
    sampling:
      probability: 1.0
# Loki URL
loki:
  url: http://localhost:3100/loki/api/v1/push

# Resilience4j properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
# Resilience4j timeout properties
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
# Resilience4j retry properties
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s


